# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Ornella Vaccarelli
# Description of the Site
description: Personal Website
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://www.moma.org/media/W1siZiIsIjM4NjQ3MCJdLFsicCIsImNvbnZlcnQiLCItcXVhbGl0eSA5MCAtcmVzaXplIDIwMDB4MTQ0MFx1MDAzZSJdXQ.jpg?sha=4c0635a9ee70d63e

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: ovaccarelli@gmail.com
facebook_username: 
twitter_username: 
instagram_username: 
linkedin_username: ornella-vaccarelli
github_username:  ovaccarelli
youtube_channel_id: 
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 

# Google Analytics
google-analytics: 

# Disqus
disqus-shortname: ovaccarelli

# Name of the Author
author-name: Ornella Vaccarelli
# URL for the Image of the Author
author-image: https://i1.rgstatic.net/ii/profile.image/670375440572434-1536841368863_Q512/Ornella-Vaccarelli.jpg
# 60 Words About the Author
author-about: <p><b> Welcome to my personal website! </p></b> <p>I am Ornella Vaccarelli, a post-doc in the <a href='https://www.tcpunilu.com/'>Theoretical Chemical Physics group</a>
              at the University of Luxembourg, lead by Prof. Alexandre Tkatchenko.
              I consider myself an ambitious and creative researcher with natural ability for critical thinking and complex problems solving.
              As a curiosity-driven, enthusiast learner and skilled theoretical physicist, I am always motivated by new challenges, prompted to find clever solutions to multidisciplinar problems.</p>
              <p>The combination of mathematical, computer science and physics skill obtained during the diffent and 
              proficuous years of studying and working in research have allowed me to acquire additional persistence 
              to my own ambition and motivation to perform excellent work, and to develop a wide variety of interests, 
              also beyond my area of expertise. Moreover, I earn significant experience 
              in scientific writing on high-impact-factor journals and in public speech at international conferences.
              Thanks to my communication and team-working skills, I established fruitful collaborations, whilst working in various 
              experimentally, computationally, and theoretically oriented multi-national groups. </p>
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/ovaccarelli

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
